# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mpetienne/r-hugo:0.1

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Render website
        run: |
          install.packages(c('kableExtra', 'wesanderson'))
          blogdown::build_site(local = FALSE, 
                               run_hugo = FALSE, 
                               build_rmd = TRUE)
          rmarkdown::render_site(encoding = 'UTF-8')         
        shell: Rscript {0}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./render
  